#!/bin/bash
# This will print the absolute path of the current script file)
#current-path_path=$(realpath $0)

# This will print out the directory name of the script path
#directory_path=$(dirname $script_path)

# This will print for us the absolute path of the current working directory
echo $dir_path
 
